services:
  db:
    image: postgres:17-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/database:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
